# Generated by Django 3.0.5 on 2020-05-06 12:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat_app', '0003_rename_author_to_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='online_participants',
            field=models.ManyToManyField(related_name='user_active_chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
