# Generated by Django 3.0.5 on 2020-05-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0004_add_online_users_to_Chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='created_by',
            field=models.CharField(default='admin', max_length=50),
        ),
    ]
